version: "3.7"
services:

  db:
    env_file: .env
    image: postgres:10
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_home:/var/lib/postgresql/data

  ogc:
    build: .
    working_dir: '/app'
    command: ["/usr/local/bin/gunicorn", "--worker-class=gevent", "--worker-connections=1000", "--bind", "0.0.0.0:5000", "app:app", "--workers=3"]
    depends_on:
      - db
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 5000:5000

volumes:
  db_home:
    external: false
