#!/bin/bash
CONTINENT=$1
COUNTRY=$2
echo "https://download.geofabrik.de/$CONTINENT/$COUNTRY-latest.osm.pbf"
wget https://download.geofabrik.de/$CONTINENT/$COUNTRY-latest.osm.pbf
osmconvert  $COUNTRY-latest.osm.pbf --all-to-nodes -o=$COUNTRY.osm
osmfilter $COUNTRY.osm  --keep="addr:country= and addr:city= and addr:street= and addr:housenumber=" \
--ignore-depemdencies --drop-relations \
| osmconvert - --csv-headline --csv-separator=';'  --csv="@lon @lat addr:country addr:postcode addr:city addr:street addr:housenumber" > $COUNTRY.csv
rm $COUNTRY.osm
rm $COUNTRY-latest.osm.pbf

#curl "http://solr:8983/solr/admin/collections?action=CREATE&name=gettingstarted3&numShards=1&collection.configName=_default"
#curl "http://solr:8983/solr/admin/collections?action=CREATE&name=$COUNTRY"
curl "http://solr:8983/solr/opengeocode/update?commit=true" --data-binary @$COUNTRY.csv -H 'Content-type:application/csv'

#curl "http://solr:8983/solr/opengeocode/update?commit=true" --data-binary @monaco.csv -H 'Content-type:application/csv'